<?php
declare(strict_types=1);

namespace Adsr\Elektron;

class Analog4Sound extends Struct {
    public function getDataMap(): array {
        return [
            'name' => new Str(16),
            'osc1_tun' => new Int8_1(),
            'osc1_fin' => new Int8_1(),
            'osc2_tun' => new Int8_1(),
            'osc2_fin' => new Int8_1(),
            'osc1_det' => new Int8_2(),
            'osc2_det' => new Int8_2(),
            'osc1_trk' => new Int8_2(),
            'osc2_trk' => new Int8_2(),
            'osc1_lev' => new Int8_2(),
            'osc2_lev' => new Int8_2(),
            'osc1_wav' => new Int8_2(),
            'osc2_wav' => new Int8_2(),
            'osc1_sub' => new Int8_2(),
            'osc2_sub' => new Int8_2(),
            'osc1_pw' => new Int8_2(),
            'osc2_pw' => new Int8_2(),
            'osc1_spd' => new Int8_2(),
            'osc2_spd' => new Int8_2(),
            'osc1_pwm' => new Int8_2(),
            'osc2_pwm' => new Int8_2(),
            'unknown_0' => new Unknown(6),
            'nois_snh' => new Int8_2(),
            'nois_fad' => new Int8_2(),
            'nois_lev' => new Int8_2(),
            'osc_am1' => new Int8_2(),
            'osc_am2' => new Int8_2(),
            'osc_smd' => new Int8_2(),
            'osc_snc' => new Int8_2(),
            'osc_bnd' => new Int8_2(),
            'osc_sli' => new Int8_2(),
            'osc_trg' => new Int8_2(),
            'osc_fad' => new Int8_2(),
            'osc_spd' => new Int8_2(),
            'osc_vib' => new Int8_2(),
            'filt1_frq' => new Int8_2(),
            'filt1_res' => new Int8_2(),
            'filt1_ovr' => new Int8_2(),
            'filt1_trk' => new Int8_2(),
            'filt1_dep' => new Int8_2(),
            'filt2_frq' => new Int8_2(),
            'filt2_res' => new Int8_2(),
            'filt2_ovr' => new Int8_2(),
            'filt2_trk' => new Int8_2(),
            'filt2_dep' => new Int8_2(),
            'unknown_1' => new Unknown(2),
            'amp_cho' => new Int8_2(),
            'amp_del' => new Int8_2(),
            'amp_rev' => new Int8_2(),
            'amp_pan' => new Int8_2(),
            'amp_vol' => new Int8_2(),
            'unknown_2' => new Unknown(2),
            'envf_atk' => new Int8_2(),
            'env2_atk' => new Int8_2(),
            'amp_atk' => new Int8_2(),
            'envf_dec' => new Int8_2(),
            'env2_dec' => new Int8_2(),
            'amp_dec' => new Int8_2(),
            'envf_sus' => new Int8_2(),
            'env2_sus' => new Int8_2(),
            'amp_sus' => new Int8_2(),
            'envf_rel' => new Int8_2(),
            'env2_rel' => new Int8_2(),
            'amp_rel' => new Int8_2(),
            'envf_shp' => new Int8_2(),
            'env2_shp' => new Int8_2(),
            'amp_shp' => new Int8_2(),
            'envf_len' => new Int8_2(),
            'env2_len' => new Int8_2(),
            'envf_dst1' => new Int8_2(),
            'envf_dst2' => new Int8_2(),
            'env2_dst1' => new Int8_2(),
            'env2_dst2' => new Int8_2(),
            'envf_dep1' => new Int16(),
            'envf_dep2' => new Int16(),
            'env2_dep1' => new Int16(),
            'env2_dep2' => new Int16(),
            'lfo' => new Analog4Lfo(),
            'unknown_3' => new Unknown(8),
            'nois_col' => new Int8_2(),
            'unknown_4' => new Unknown(6),
            'osc_drift' => new Int8_1(),
            'portamento' => new Int8_1(),
            'legato_mode' => new Int8_1(),
            'vel_to_vol' => new Int8_1(),
            'f1_res_boost' => new Int8_1(),
            'unknown_5' => new Unknown(3),
            'settings' => new Analog4SoundSettings(),
        ];
    }
}
